// Boost Software License - Version 1.0 - August 17th, 2003

// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:

// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#include "Camera.hpp"

namespace rt::camera {

/// Create a ray travelling from the camera to the scene
/// \param[in] u Horizontal offset vector used to move the ray across the scene
/// \param[in] v Vertical offset vector used to move the ray along the scene
/// \returns A ray from the camera to the scene
ray::Ray Camera::getRay(double u, double v) const noexcept
{
  auto const rd = m_lensRadius * vec3::getRandomVecInUnitDisk();
  auto const offset = m_u * rd.x() + m_v * rd.y();

  return ray::Ray(m_origin + offset, m_lowerLeftCorner + (u * m_horizontal) + (v * m_vertical) - m_origin - offset);
}

}   // namespace rt::camera
